[meta]
name = "CAMS EAC4 to GOCART dust scheme"
version = 1

[units]
source = "kg"
target = "ug"

[aliases_source]
CAMSD1 = "aermr04"
CAMSD2 = "aermr05"
CAMSD3 = "aermr06"

[aliases_target]

[species_map]
DUST_1 = { CAMSD1 = 0.963777, CAMSD2 = 1.0, CAMSD3 = 0.016303 }
DUST_2 = { CAMSD3 = 0.190836 }
DUST_3 = { CAMSD3 = 0.29703 }
DUST_4 = { CAMSD3 = 0.353956 }
DUST_5 = { CAMSD3 = 0.106119 }
