# Upload package to pypi everytime a release is created
name: Upload release to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build
        run: poetry build
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


  pypi-publish:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: pypi
      url: https://pypi.org/p/interpolator-for-wrfchem

    permissions:
      id-token: write

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1